config/routes.rb
Rails.application.routes.draw do

  resources :groups

  root 'groups#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	def index
		@groups = Group.all
	end

	def show

	end

	def new
		@group = Group.new
	end

	def edit

	end

	def create
		@group = Group.create(group_params)

		if @group.save
			redirect_to groups_path
		else
	end

	def update

	end

	def destroy

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def notice_message
		alert_types = { notice: :success, alert: :danger}

		close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true}
		close_button = content_tag(:button, "x", close_button_options)

		alerts = flash.map do |type, message|
			alert_content = close_button + message

			alert_type = alert_types[type.to_sym] || type
			alert_class = "alert alert-#{alert_type} alert-dismissable"
			content_tag(:div, alert_content, class: alert_class)
		end

		alerts.join("\n").html_safe
	end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
	<p class="text-center">
		Copyright 2014 Rails101<br>
		Design by Jones
	</p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" href="/">Rails 101</a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to("登入",'#') %></li>
			</ul>
		</div>
	</div>
</nav>

app/views/groups/index.html.erb
<div class="col-md-12">
<div class="group">
<%= link_to("New Group", new_group_path, :class=> "btn btn-primary pull-right")%>
</div>
<table class="table table-hover">
	<thead>
		<tr>
			<td>#</td>
			<td>title</td>
			<td>Description</td>
		</tr>
	</thead>
	<tbody>
		<% @groups.each do |group| %>
			<tr>
				<td>#</td>
				<td><%= link_to(group.title, group_path(group)) %></td>
				<td><%= group.description %></td>
				<td>
					<%= link_to("Edit", edit_group_path(group), class: "btn btn-sm btn-default")%>
					<%= link_to("Delete", group_path(group), class: "btn btn-sm btn-default", method: :delete, data: {confirm: "Are you sure?"}) %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
	<h1>新增討論版</h1>
	<hr>
	<%= simple_form_for @group do |f| %>
		<div class="form-group">
		<%= f.input :title, input_html: {class: "form-control"}%>
		<%= f.input :description, input_html: { class: "form-control"}%>
		</div>
		<%= f.submit "Submit", disable_with: 'Submitting....', class: "btn btn-primary" %>
	<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails101s</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
	<%= render "common/navbar" %>
	<%= notice_message %>
	<%= yield %>
</div>
	<%= render "common/footer" %>
</body>
</html>